sitename: Ruby on Rails - Responsive Mobile - eCommerce | Downshift Labs
tagline: Augment your online presence

production_url: http://downshiftlabs.com
url: http://downshiftlabs.com

safe: false
auto: true
baseurl: /

markdown: rdiscount
